services:
    anvil:
        image: ghcr.io/foundry-rs/foundry:nightly-503792a1dbadd901a4c02f6fcd1de1caff1573ff
        ports: ['8545:8545']
        entrypoint:
            [
                'anvil',
                '--fork-url',
                'https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}',
                '--fork-block-number',
                '6093396',
                '--host',
                '0.0.0.0',
            ]
        platform: linux/amd64/v8
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'wget -q -O - http://0.0.0.0:8545 --post-data ''{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'' --header=''Content-Type: application/json'' || exit 1',
                ]
            interval: 2s
            timeout: 5s
            retries: 5

    alto:
        image: chnejohnson/alto:0.0.11
        ports: ['4337:4337']
        command: --config alto.config.json
        volumes:
            - ./alto.config.json:/app/alto.config.json
        depends_on:
            anvil:
                condition: service_healthy
